source 'https://github.com/cocoapods/specs.git'

platform :ios, '7.0'

xcodeproj 'JazzHandsDemo'

def install_pods
    pod 'JazzHands', :path => '../JazzHands.podspec'
    pod 'Masonry'
end

target :JazzHandsDemo do
    install_pods
end

target :JazzHandsTests, :exclusive => true do
    install_pods
    pod 'Specta'
    pod 'Expecta'
end
