#!/bin/sh

set -e

xcodebuild \
-workspace JazzHandsDemo/JazzHandsDemo.xcworkspace \
-scheme JazzHandsDemo \
-sdk iphonesimulator \
clean build \
ONLY_ACTIVE_ARCH=NO \
RUN_CLANG_STATIC_ANALYZER=YES \
CLANG_STATIC_ANALYZER_MODE=deep | xcpretty -c
