#!/bin/sh

export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

set -o pipefail && xcodebuild \
-workspace JazzHandsDemo/JazzHandsDemo.xcworkspace \
-scheme JazzHandsDemo \
-sdk iphonesimulator \
clean analyze \
ONLY_ACTIVE_ARCH=NO | xcpretty -c
